substitutions:
  device_name: refrigerator
  pretty_name: Refrigerator
esphome:
  name: refrigerator
  platform: ESP8266
  board: esp01_1m
  build_path: ./build/refrigerator
  board_flash_mode: dout
  arduino_version: espressif8266@2.2.3
  esp8266_restore_from_flash: false
  libraries: []
  includes: []
  platformio_options: {}
wifi:
  ap:
    ssid: refrigerator
    password: !secret 'wifi_password_2'
    ap_timeout: 1min
  reboot_timeout: 120s
  power_save_mode: NONE
  networks:
  - ssid: !secret 'wifi_ssid_1'
    password: !secret 'wifi_password_2'
    priority: 0.0
  - ssid: !secret 'wifi_ssid_2'
    password: !secret 'wifi_password_2'
    priority: 0.0
  output_power: 20.0
  domain: .local
  fast_connect: false
  use_address: 192.168.1.181
captive_portal: {}
logger:
  level: DEBUG
  hardware_uart: UART0
  esp8266_store_log_strings_in_flash: true
  tx_buffer_size: 512
  baud_rate: 115200
  logs: {}
api:
  password: !secret 'password'
  port: 6053
  reboot_timeout: 15min
ota:
  password: !secret 'password'
  port: 8266
  safe_mode: true
sensor:
- platform: cse7766
  current:
    name: Refrigerator Current
    accuracy_decimals: 2
    icon: mdi:flash
    unit_of_measurement: A
    force_update: false
  voltage:
    name: Refrigerator Voltage
    accuracy_decimals: 1
    icon: mdi:flash
    unit_of_measurement: V
    force_update: false
  power:
    name: Refrigerator Power
    accuracy_decimals: 1
    icon: mdi:flash
    unit_of_measurement: W
    force_update: false
  update_interval: 10s
text_sensor:
- platform: version
  name: Refrigerator ESPHome Version
  icon: mdi:new-box
- platform: wifi_info
  ip_address:
    name: Refrigerator IP Address
    icon: mdi:ip-network
  ssid:
    name: Refrigerator SSID
    icon: mdi:access-point-network
  bssid:
    name: Refrigerator BSSID
    icon: mdi:table-network
output:
- platform: esp8266_pwm
  id: refrigerator_led
  pin:
    number: 13
    inverted: false
    mode: OUTPUT
  inverted: true
  frequency: 1000.0
light:
- platform: monochromatic
  name: Refrigerator LED
  output: refrigerator_led
  restore_mode: RESTORE_DEFAULT_OFF
  gamma_correct: 2.8
  default_transition_length: 1s
switch:
- platform: gpio
  name: Refrigerator CH 1
  pin:
    number: 12
    inverted: false
    mode: OUTPUT
  id: relay1
  restore_mode: RESTORE_DEFAULT_ON
  interlock_wait_time: 0ms
- platform: restart
  name: Refrigerator Restart
  icon: mdi:restart
binary_sensor:
- platform: gpio
  pin:
    number: 0
    mode: INPUT_PULLUP
    inverted: false
  name: Refrigerator Button
  on_press:
  - then:
    - switch.toggle:
        id: relay1
- platform: status
  name: Refrigerator Status
  device_class: connectivity
uart:
- rx_pin: 3
  baud_rate: 4800
  stop_bits: 1

