substitutions:
  pretty_name: "Decorative Lights"
  device_name: "decorative_lights"

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini
  build_path: "./build/${device_name}"

<<: !include ../../common/standard.yaml
<<: !include ../../common/sensor/standard.yaml
<<: !include ../../common/text_sensor/standard.yaml
<<: !include ./standard.yaml

light:
  - platform: fastled_clockless
    chipset: WS2811
    restore_mode: ALWAYS_OFF
    pin: D6
    num_leds: 12
    rgb_order: BRG
    id: "${device_name}_test"
    name: "${pretty_name} (Test)"
    effects:
      - strobe:
          name: "White Flashing Strobe"
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 100%
              blue: 100%
              duration: 100ms
            - state: false
              duration: 100ms
      - addressable_rainbow:
          name: "Rainbow"
      - addressable_color_wipe:
          name: "American Flag"
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 3
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 3
      - addressable_color_wipe:
          name: "Color Wipe"
      - addressable_scan:
          name: "Scan"
      - addressable_twinkle:
          name: "Twinkle"
      - addressable_random_twinkle:
          name: "Random Twinkle"
      - addressable_fireworks:
          name: "Fireworks"
      - addressable_flicker:
          name: "Flicker"

