substitutions:
  device_name: fronthallstrip
  pretty_name: "Front Hall Strip"
  ch1_restore_mode: RESTORE_DEFAULT_OFF
  ch2_restore_mode: RESTORE_DEFAULT_OFF
  ch3_restore_mode: RESTORE_DEFAULT_OFF
  ch4_restore_mode: RESTORE_DEFAULT_OFF
  ip_address: 192.168.99.24

<<: !include ../../devices/wt8266-s1/4-plug-power-strip-static.yaml
