substitutions:
  device_name: fwdisplaystrip
  pretty_name: "FW Tank Display Strip"
  ch1_restore_mode: RESTORE_DEFAULT_OFF
  ch2_restore_mode: RESTORE_DEFAULT_OFF
  ch3_restore_mode: ALWAYS_OFF
  ch4_restore_mode: RESTORE_DEFAULT_OFF
  ip_address: 192.168.99.25

<<: !include ../../devices/wt8266-s1/4-plug-power-strip-static.yaml
