esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m
  build_path: "./build/${device_name}"

<<: !include ../../common/wifi.yaml
<<: !include ../../common/captive_portal.yaml
<<: !include ../../common/api.yaml
<<: !include ../../common/ota.yaml

<<: !include ../../common/text_sensor/standard.yaml

status_led:
  pin: GPIO13

switch:
  - platform: gpio
    name: "${pretty_name} CH 1"
    pin: GPIO12
    id: relay1
    restore_mode: "${restore_mode}"

  - platform: restart
    name: "${pretty_name} Restart"

logger:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: false
    name: "${pretty_name} Button"
    on_press:
      - switch.toggle: relay1
  - platform: status
    name: "${pretty_name} Status"

# uart:
#   rx_pin: RX
#   baud_rate: 4800
