substitutions:
  device_name: patio_switches
  pretty_name: "Patio Switches"
  ip_address: 192.168.99.46

esphome:
  name: $device_name
  platform: ESP8266
  board: nodemcuv2
  build_path: "./build/${device_name}"

<<: !include ../../common/standard-static.yaml
<<: !include ../../common/sensor/standard.yaml
<<: !include ../../common/text_sensor/standard.yaml

status_led:
  pin: 
    number: D4
    inverted: true

binary_sensor:
  - platform: status
    name: "${pretty_name} Status"

switch:
  - platform: gpio
    name: "${pretty_name} CH 1"
    restore_mode: ALWAYS_ON
    pin: D1
  - platform: gpio
    name: "${pretty_name} CH 2"
    restore_mode: ALWAYS_ON
    pin: D2
