esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m
  build_path: "./build/${device_name}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name}"
    password: !secret wifi_password

captive_portal:

logger:

api:
  password: !secret password

ota:
  password: !secret password

output:
  - platform: esp8266_pwm
    id: "${device_name}_led"
    pin: GPIO13
    inverted: True

light:
  - platform: monochromatic
    name: "${pretty_name} LED"
    output: "${device_name}_led"

sensor:
  - platform: wifi_signal
    name: "${pretty_name} WiFi Signal"
    update_interval: 1200s

  - platform: uptime
    name: "${pretty_name} Uptime"

text_sensor:
  - platform: version
    name: "${pretty_name} Version"