substitutions:
  device_name: bumblebee_strip
  pretty_name: "Bumblebee Strip"
  ip_address: 192.168.99.40
  ch1_restore_mode: ALWAYS_ON
  ch2_restore_mode: ALWAYS_ON
  ch3_restore_mode: ALWAYS_ON
  ch4_restore_mode: ALWAYS_ON

<<: !include ../../devices/wt8266-s1/4-plug-power-strip-static.yaml
