substitutions:
  device_name: cnc_table_light
  pretty_name: "CNC Table Light"
  status_led: GPIO2
  restore_mode: RESTORE_DEFAULT_OFF
  ip_address: 192.168.99.38

<<: !include ../../devices/esp-01/relay-static.yaml
